import React from 'react';
import { Recommendation } from './types';
import { Sparkles, DollarSign, AlertCircle, ArrowUpRight, CheckCircle2 } from 'lucide-react';

interface RecommendationsViewProps {
  recommendations: Recommendation[];
}

export const RecommendationsView: React.FC<RecommendationsViewProps> = ({ recommendations }) => {
  const totalSavings = recommendations.reduce((sum, r) => sum + r.estimatedSavings, 0);

  const getSeverityStyles = (severity: Recommendation['severity']) => {
    switch (severity) {
      case 'critical':
        return 'bg-red-950/40 border-red-800 text-red-400';
      case 'high':
        return 'bg-orange-950/40 border-orange-850 text-orange-400';
      case 'medium':
        return 'bg-yellow-950/40 border-yellow-850 text-yellow-400';
      default:
        return 'bg-blue-950/40 border-blue-900 text-blue-400';
    }
  };

  return (
    <div className="space-y-6">
      {/* View Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-400" /> AI Recommendation Engine
          </h1>
          <p className="text-slate-400 text-xs mt-1">Automatic audits generated by cloud intelligence rule metrics</p>
        </div>
        <div className="p-3 bg-purple-950/20 border border-purple-900/60 rounded-xl flex items-center gap-3 text-xs">
          <DollarSign className="w-4 h-4 text-purple-400" />
          <div>
            <div className="text-slate-400 font-medium">Estimated Monthly Savings</div>
            <div className="text-sm font-extrabold text-white">${totalSavings.toFixed(2)}/mo</div>
          </div>
        </div>
      </div>

      {recommendations.length === 0 ? (
        <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-12 text-center flex flex-col items-center justify-center">
          <CheckCircle2 className="w-12 h-12 text-emerald-500 mb-3" />
          <h3 className="text-sm font-bold text-white uppercase tracking-wider">No Optimization Recommendations</h3>
          <p className="text-slate-500 text-[10px] mt-1 max-w-[280px]">
            Your architecture matches AWS Well-Architected Framework guidelines. Add more components or scale capacity to trigger scans.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {recommendations.map(rec => (
            <div
              key={rec.id}
              className={`p-5 rounded-xl border flex flex-col md:flex-row items-start gap-4 transition-all hover:scale-[1.005] ${getSeverityStyles(
                rec.severity
              )}`}
            >
              <div className="p-2 rounded-lg bg-slate-950 border border-slate-850 self-start">
                <AlertCircle className="w-5 h-5" />
              </div>
              <div className="flex-1 space-y-2">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="text-[9px] font-extrabold uppercase px-2 py-0.5 rounded-full border bg-slate-950">
                    {rec.service}
                  </span>
                  <span className="text-[9px] font-extrabold uppercase px-2 py-0.5 rounded-full border bg-slate-950">
                    {rec.severity}
                  </span>
                  <span className="text-[10px] text-slate-400 font-medium italic">{rec.impact}</span>
                </div>
                <h3 className="text-sm font-bold text-white">{rec.title}</h3>
                <p className="text-slate-350 text-[11px] leading-relaxed">{rec.description}</p>
                <div className="pt-2 border-t border-slate-900/40 text-[10px]">
                  <span className="font-bold uppercase text-slate-400 mr-1.5">Action Plan:</span>
                  <span className="text-slate-300 font-mono">{rec.suggestedFix}</span>
                </div>
              </div>

              {rec.estimatedSavings > 0 && (
                <div className="text-right self-stretch md:self-center border-t md:border-t-0 md:border-l border-slate-900/45 pt-3 md:pt-0 md:pl-5 flex md:flex-col items-center md:items-end justify-between min-w-[120px]">
                  <span className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Savings</span>
                  <span className="text-lg font-extrabold text-emerald-400 font-mono mt-1 flex items-center">
                    +${rec.estimatedSavings.toFixed(2)}
                    <ArrowUpRight className="w-3.5 h-3.5" />
                  </span>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
